#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

cd examples/app-router
yalc remove --all
yarn add "next-theme-kit@latest"

cd ..

cd pages-router
yalc remove --all
yarn add "next-theme-kit@latest"

cd ..

yarn lint-staged